// ppt-creator skill — Markdown / JSON slide spec → .pptx binary (pptxgenjs, pure JS)
import pptxgen from "pptxgenjs";
import fs from "node:fs";
import path from "node:path";

function parseArgs(argv) {
  const opts = { input: null, out: null, theme: "light", title: null, author: null, layout: "16x9", help: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--out") opts.out = argv[++i];
    else if (a === "--theme") opts.theme = argv[++i];
    else if (a === "--title") opts.title = argv[++i];
    else if (a === "--author") opts.author = argv[++i];
    else if (a === "--layout") opts.layout = argv[++i];
    else if (a === "-h" || a === "--help") opts.help = true;
    else if (!a.startsWith("--")) opts.input = a;
  }
  return opts;
}

function readInput(opts) {
  if (!opts.input || opts.input === "-") return fs.readFileSync(0, "utf8");
  return fs.readFileSync(opts.input, "utf8");
}

// Markdown → slides
function parseMarkdown(md) {
  const lines = md.replace(/\r\n?/g, "\n").split("\n");
  const slides = [];
  let cur = null;
  const push = () => {
    if (cur && (cur.title || cur.section || cur.bullets.length)) slides.push(cur);
    cur = null;
  };
  for (const line of lines) {
    if (/^\s*-{3,}\s*$/.test(line)) { push(); continue; }
    if (!cur) cur = { type: "content", title: null, subtitle: null, section: null, bullets: [], notes: [] };
    const h1 = line.match(/^#\s+(.*)$/);
    const h2 = line.match(/^##\s+(.*)$/);
    const h3 = line.match(/^###\s+(.*)$/);
    const note = line.match(/^>\s?(.*)$/);
    if (h1) { cur.title = h1[1].trim(); }
    else if (h2) { cur.section = h2[1].trim(); cur.type = "section"; }
    else if (h3) { if (!cur.subtitle) cur.subtitle = h3[1].trim(); }
    else if (note) { cur.notes.push(note[1].trim()); }
    else {
      const b = line.match(/^(\s*)[-*+]\s+(.*)$/);
      if (b) {
        const level = Math.floor((b[1] || "").length / 2);
        cur.bullets.push({ text: b[2].trim(), level });
      } else if (line.trim() !== "") {
        cur.bullets.push({ text: line.trim(), level: 0 });
      }
    }
  }
  push();
  // First slide with a title and no bullets → cover slide.
  if (slides.length && slides[0].title && slides[0].bullets.length === 0 && slides[0].type !== "section") {
    slides[0].type = "title";
  }
  return slides;
}

// JSON spec → slides
function parseSpec(text) {
  const data = JSON.parse(text);
  if (!Array.isArray(data.slides)) throw new Error("JSON spec must be { slides: [...] }");
  return data.slides.map((s) => ({
    type: s.type || "content",
    title: s.title || null,
    subtitle: s.subtitle || null,
    section: s.section || null,
    bullets: Array.isArray(s.bullets)
      ? s.bullets.map((b) => (typeof b === "string" ? { text: b, level: 0 } : { text: b.text, level: b.level || 0 }))
      : [],
    notes: Array.isArray(s.notes) ? s.notes : (s.notes ? [s.notes] : []),
    background: s.background || null,
  }));
}

const THEMES = {
  light: { bg: "FFFFFF", title: "1A1A1A", text: "333333", accent: "1F6FEB" },
  dark: { bg: "121212", title: "FFFFFF", text: "E6E6E6", accent: "4C9AFF" },
};

const LAYOUTS = {
  "16x9": { name: "LAYOUT_WIDE", w: 13.33, h: 7.5 },
  "4x3": { name: "LAYOUT_4x3", w: 10, h: 7.5 },
};

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help || (!opts.input && process.stdin.isTTY)) {
    process.stderr.write(
      "ppt-creator skill — Markdown/JSON → .pptx\n" +
      "Usage: node build.js <input.md|input.json|-> [--out path.pptx] [--theme dark|light] " +
      "[--title T] [--author A] [--layout 16x9|4x3]\n"
    );
    process.exit(0);
  }

  const text = readInput(opts);
  const theme = THEMES[opts.theme] || THEMES.light;
  const layout = LAYOUTS[opts.layout] || LAYOUTS["16x9"];

  let slides;
  try {
    slides = opts.input && /\.json$/i.test(opts.input) ? parseSpec(text) : parseMarkdown(text);
  } catch (e) {
    process.stderr.write("Parse error: " + e.message + "\n");
    process.exit(1);
  }
  if (!slides.length) { process.stderr.write("No slides parsed.\n"); process.exit(1); }

  const pptx = new pptxgen();
  pptx.layout = layout.name;
  pptx.author = opts.author || "MyAgent";
  pptx.title = opts.title || slides[0]?.title || "Presentation";
  pptx.subject = "Generated by ppt-creator skill";

  const W = layout.w, H = layout.h;

  for (const s of slides) {
    const slide = pptx.addSlide();
    slide.background = { color: s.background || theme.bg };

    if (s.type === "title") {
      slide.addText(s.title || "", {
        x: 0.5, y: H / 2 - 1, w: W - 1, h: 1.3, fontSize: 40, bold: true,
        color: theme.title, align: "center", fontFace: "Arial",
      });
      if (s.subtitle) {
        slide.addText(s.subtitle, {
          x: 0.5, y: H / 2 + 0.3, w: W - 1, h: 0.8, fontSize: 20,
          color: theme.text, align: "center", fontFace: "Arial",
        });
      }
    } else if (s.type === "section") {
      slide.addText(s.section || s.title || "", {
        x: 0.5, y: H / 2 - 0.5, w: W - 1, h: 1, fontSize: 32, bold: true,
        color: theme.accent, align: "center", fontFace: "Arial",
      });
    } else {
      if (s.title) {
        slide.addText(s.title, {
          x: 0.5, y: 0.3, w: W - 1, h: 0.9, fontSize: 28, bold: true,
          color: theme.title, fontFace: "Arial",
        });
      }
      if (s.bullets.length) {
        const items = s.bullets.map((b) => ({
          text: b.text,
          options: {
            bullet: true,
            indentLevel: Math.min(b.level || 0, 4),
            color: theme.text,
            fontSize: Math.max(14, 20 - 2 * Math.min(b.level || 0, 2)),
            fontFace: "Arial",
          },
        }));
        slide.addText(items, { x: 0.7, y: 1.4, w: W - 1.4, h: H - 1.8, valign: "top" });
      }
    }
    if (s.notes && s.notes.length) slide.addNotes(s.notes.join("\n"));
  }

  let outPath = opts.out;
  if (!outPath) {
    const base = opts.input && opts.input !== "-"
      ? opts.input.replace(/\.(md|markdown|json)$/i, "")
      : "presentation";
    outPath = base + ".pptx";
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  const buf = await pptx.write({ outputType: "nodebuffer" });
  fs.writeFileSync(outPath, buf);
  process.stdout.write(outPath + "\n");
}

main().catch((e) => {
  process.stderr.write("Error: " + (e?.message || String(e)) + "\n");
  process.exit(1);
});